### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'entity'

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#365]
Hi all, another migrations bug, just tried it with the new json fix (this isn't json related).   When adding in another class with a lambda 

```
class Servidor(db.Entity):
    user = Optional(lambda: User)
    ubicacion = Optional(unicode)
    ubicacion_ip = Optional(unicode)
    vm = Optional(unicode)
    configuration = Optional(Json)
    ipv6 = Optional(unicode)
    ipv4 = Optional(unicode)
    sshkeys = Optional(unicode)
    label = Optional(unicode)
    nombre = Optional(unicode)
    tickets = Set(lambda:Ticket)
    dia_creado = Optional(datetime, default=datetime.now)
    dia_destruido = Optional(datetime)
    status = Optional(unicode, default='creado')
    historias = Set(lambda: Historia)

class Historia(db.Entity):
    servidor = Optional(lambda:Servidor)
    dia = Optional(datetime, default=datetime.now)
    action = Optional(unicode)

```
The problem is it spits this out when I try and run `python migrate.py make`
```
GET NEW CONNECTION
RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
DISCONNECT
DISCONNECT
Traceback (most recent call last):
  File "migrate.py", line 5, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 684, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 96, in _migrate
    return graph.make(db=db, empty=empty, custom=custom, description=name)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/migration.py", line 289, in make
    generated = writer.as_string()
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 349, in as_string
    body = self._get_operations_block(imports)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 314, in _get_operations_block
    self.operations = self._get_ops()
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 224, in _get_ops
    if prev_attr.entity is not prev_entity: assert False, 'Not implemented'
AttributeError: 'NoneType' object has no attribute 'entity'

```

**Comment by sashaaero** [comment]
Thanks for reporting. Should work now.

**Comment by nadermx** [comment]
Unfortunatly it still doesn't seem to work when I want to add in a new class.  

```
Traceback (most recent call last):
  File "migrate.py", line 5, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 684, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 96, in _migrate
    return graph.make(db=db, empty=empty, custom=custom, description=name)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/migration.py", line 289, in make
    generated = writer.as_string()
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 349, in as_string
    body = self._get_operations_block(imports)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 314, in _get_operations_block
    self.operations = self._get_ops()
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 224, in _get_ops
    if prev_attr.entity is not prev_entity: assert False, 'Not implemented'
AttributeError: 'NoneType' object has no attribute 'entity'
```

**Comment by nadermx** [comment]
@sashaaero I currently have say for example 

```
class Servidor(db.Entity):
    user = Optional(lambda: User)
    ubicacion = Optional(unicode)
    ubicacion_ip = Optional(unicode)
    vm = Optional(unicode)
    configuration = Optional(Json)
    ipv6 = Optional(unicode)
    ipv4 = Optional(unicode)
    sshkeys = Optional(unicode)
    label = Optional(unicode)
    nombre = Optional(unicode)
    tickets = Set(lambda:Ticket)
    dia_creado = Optional(datetime, default=datetime.now)
    dia_destruido = Optional(datetime)
    status = Optional(unicode, default='creado')
    historias = Set(lambda: Historia)
```
And I'm trying to add in `    resize_history = Set(lambda:Resize)`  right after 'histroias' then define the class so it looks like this 
```
class Servidor(db.Entity):
    user = Optional(lambda: User)
    ubicacion = Optional(unicode)
    ubicacion_ip = Optional(unicode)
    vm = Optional(unicode)
    configuration = Optional(Json)
    ipv6 = Optional(unicode)
    ipv4 = Optional(unicode)
    sshkeys = Optional(unicode)
    label = Optional(unicode)
    nombre = Optional(unicode)
    tickets = Set(lambda:Ticket)
    dia_creado = Optional(datetime, default=datetime.now)
    dia_destruido = Optional(datetime)
    status = Optional(unicode, default='creado')
    historias = Set(lambda: Historia)
    resize_history = Set(lambda:Resize)

class Resize(db.Entity):
    servidor = Optional(lambda: Servidor)
    dia_resized = Optional(datetime, default=datetime.now)
    configuration = Optional(Json)

```

**Comment by sashaaero** [comment]
Hello. I looked your stacktrace and I see that you forgot to upgrade pony from github. 
Your stackstrace says
`File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/writer.py", line 224, in _get_ops
    if prev_attr.entity is not prev_entity: assert False, 'Not implemented'`
but if you watch [here](https://github.com/ponyorm/pony/commit/c77b861a7e53efe86bbd1fc107aa11367d8f3bb9#diff-fdbe958db8e402b04924fef652bf11b2L224) you can see that this line is now 226.
